SELECT
    CUSTOMER_ORDER.ORDER_ID
  , CUSTOMER.CUSTOMER_ID
  , CUSTOMER_ORDER.ORDER_DATE
  , CUSTOMER_ORDER.SHIP_DATE
  , CUSTOMER.NAME
  , CUSTOMER.STREET_ADDRESS
  , CUSTOMER.CITY
  , CUSTOMER.STATE
  , CUSTOMER.ZIP
  , CUSTOMER_ORDER.PRODUCT_ID
  , CUSTOMER_ORDER.ORDER_QTY
FROM
    CUSTOMER
INNER JOIN
    CUSTOMER_ORDER
ON
    CUSTOMER.CUSTOMER_ID = CUSTOMER_ORDER.CUSTOMER_ID;