SELECT
    *
FROM
    CUSTOMER;


SELECT
    CUSTOMER_ORDER.ORDER_ID
  , CUSTOMER.CUSTOMER_ID
  , CUSTOMER_ORDER.ORDER_DATE
  , CUSTOMER_ORDER.SHIP_DATE
  , CUSTOMER.NAME
  , CUSTOMER.STREET_ADDRESS
  , CUSTOMER.CITY
  , CUSTOMER.STATE
  , CUSTOMER.ZIP
  , PRODUCT_ID
  , CUSTOMER_ORDER.ORDER_QTY
FROM
    CUSTOMER
LEFT JOIN
    CUSTOMER_ORDER
ON
    CUSTOMER.CUSTOMER_ID = CUSTOMER_ORDER.CUSTOMER_ID;


SELECT
    CUSTOMER.CUSTOMER_ID
  , CUSTOMER.NAME AS CUSTOMER_NAME
FROM
    CUSTOMER
LEFT JOIN
    CUSTOMER_ORDER
ON
    CUSTOMER.CUSTOMER_ID = CUSTOMER_ORDER.CUSTOMER_ID
WHERE
    CUSTOMER_ORDER.CUSTOMER_ID IS NULL;