SELECT
    CUSTOMER_ORDER.ORDER_ID
  , CUSTOMER.CUSTOMER_ID
  , CUSTOMER.NAME AS CUSTOMER_NAME
  , CUSTOMER.STREET_ADDRESS
  , CUSTOMER.CITY
  , CUSTOMER.STATE
  , CUSTOMER.ZIP
  , CUSTOMER_ORDER.ORDER_DATE
  , PRODUCT.PRODUCT_ID
  , PRODUCT.DESCRIPTION
  , CUSTOMER_ORDER.ORDER_QTY
FROM
    CUSTOMER
INNER JOIN
    CUSTOMER_ORDER
ON
    CUSTOMER.CUSTOMER_ID = CUSTOMER_ORDER.CUSTOMER_ID
INNER JOIN
    PRODUCT
ON
    CUSTOMER_ORDER.PRODUCT_ID = PRODUCT.PRODUCT_ID;


SELECT
    CUSTOMER_ORDER.ORDER_ID
  , CUSTOMER.CUSTOMER_ID
  , CUSTOMER.NAME AS CUSTOMER_NAME
  , CUSTOMER.STREET_ADDRESS
  , CUSTOMER.CITY
  , CUSTOMER.STATE
  , CUSTOMER.ZIP
  , CUSTOMER_ORDER.ORDER_DATE
  , PRODUCT.PRODUCT_ID
  , PRODUCT.DESCRIPTION
  , CUSTOMER_ORDER.ORDER_QTY
  , ORDER_QTY * PRICE AS REVENUE
FROM
    CUSTOMER
INNER JOIN
    CUSTOMER_ORDER
ON
    CUSTOMER.CUSTOMER_ID = CUSTOMER_ORDER.CUSTOMER_ID
INNER JOIN
    PRODUCT
ON
    CUSTOMER_ORDER.PRODUCT_ID = PRODUCT.PRODUCT_ID;


SELECT
    CUSTOMER_ORDER.ORDER_ID
  , CUSTOMER.NAME AS CUSTOMER_NAME
  , SUM(ORDER_QTY * PRICE) AS TOTAL_REVENUE
FROM
    CUSTOMER
INNER JOIN
    CUSTOMER_ORDER
ON
    CUSTOMER.CUSTOMER_ID = CUSTOMER_ORDER.CUSTOMER_ID
INNER JOIN
    PRODUCT
ON
    CUSTOMER_ORDER.PRODUCT_ID = PRODUCT.PRODUCT_ID
GROUP BY
    1,2;


SELECT
    CUSTOMER_ORDER.ORDER_ID
  , CUSTOMER.NAME AS CUSTOMER_NAME
  , SUM(ORDER_QTY * PRICE) AS TOTAL_REVENUE
FROM
    CUSTOMER
LEFT JOIN
    CUSTOMER_ORDER
ON
    CUSTOMER.CUSTOMER_ID = CUSTOMER_ORDER.CUSTOMER_ID
LEFT JOIN
    PRODUCT
ON
    CUSTOMER_ORDER.PRODUCT_ID = PRODUCT.PRODUCT_ID
GROUP BY
    1,
    2;


SELECT
    CUSTOMER_ORDER.ORDER_ID
  , CUSTOMER.NAME AS CUSTOMER_NAME
  , COALESCE(SUM(ORDER_QTY * PRICE), 0) AS TOTAL_REVENUE
FROM
    CUSTOMER
LEFT JOIN
    CUSTOMER_ORDER
ON
    CUSTOMER.CUSTOMER_ID = CUSTOMER_ORDER.CUSTOMER_ID
LEFT JOIN
    PRODUCT
ON
    CUSTOMER_ORDER.PRODUCT_ID = PRODUCT.PRODUCT_ID
GROUP BY
    1,
    2;