CREATE TABLE COMPANY (
    COMPANY_ID INTEGER PRIMARY KEY AUTOINCREMENT
  , NAME VARCHAR(30) NOT NULL
  , DESCRIPTION VARCHAR(30) NOT NULL
  , PRIMARY_CONTACT_ATTENDEE_ID INTEGER NOT NULL
  , FOREIGN KEY (PRIMARY_CONTACT_ATTENDEE_ID) REFERENCES ATTENDEE(ATTENDEE_ID)
);


CREATE TABLE ROOM (
    ROOM_ID INTEGER PRIMARY KEY AUTOINCREMENT
   ,FLOOR_NUMBER INTEGER NOT NULL
   , SEAT_CAPACITY INTEGER NOT NULL
);


CREATE TABLE PRESENTATION (
    PRESENTATION_ID INTEGER PRIMARY KEY AUTOINCREMENT
  , BOOKED_COMPANY_ID INTEGER NOT NULL
  , BOOKED_ROOM_ID INTEGER NOT NULL
  , START_TIME TIME
  , END_TIME TIME
  , FOREIGN KEY (BOOKED_COMPANY_ID) REFERENCES COMPANY(COMPANY_ID)
  , FOREIGN KEY (BOOKED_ROOM_ID) REFERENCES ROOM(ROOM_ID)
);


CREATE TABLE  ATTENDEE (
    ATTENDEE_ID INTEGER PRIMARY KEY AUTOINCREMENT
  , FIRST_NAME VARCHAR(30) NOT NULL
  , LAST_NAME VARCHAR(30) NOT NULL
  , PHONE INTEGER
  , EMAIL VARCHAR(30)
  , VIP BOOLEAN DEFAULT (0)
);


CREATE TABLE  PRESENTATION_ATTENDEE (
    TICKET_ID INTEGER PRIMARY KEY AUTOINCREMENT
  , PRESENTATION_ID INTEGER
  , ATTENDEE_ID INTEGER
  , FOREIGN KEY (PRESENTATION_ID) REFERENCES PRESENTATION(PRESENTATION_ID)
  , FOREIGN KEY (ATTENDEE_ID) REFERENCES ATTENDEE(ATTENDEE_ID)
);


DROP TABLE IF EXISTS COMPANY;