SELECT
    COMPANY.NAME AS BOOKED_COMPANY
  , ROOM.ROOM_ID AS ROOM_NUMBER
  , ROOM.FLOOR_NUMBER AS FLOOR
  , ROOM.SEAT_CAPACITY AS SEATS
  , START_TIME
  , END_TIME
FROM
    PRESENTATION
INNER JOIN
    COMPANY
ON
    PRESENTATION.BOOKED_COMPANY_ID = COMPANY.COMPANY_ID
INNER JOIN
    ROOM
ON
    PRESENTATION.BOOKED_ROOM_ID = ROOM.ROOM_ID;


CREATE VIEW PRESENTATION_VIEW AS
SELECT
    COMPANY.NAME AS BOOKED_COMPANY
  , ROOM.ROOM_ID AS ROOM_NUMBER
  , ROOM.FLOOR_NUMBER AS FLOOR
  , ROOM.SEAT_CAPACITY AS SEATS
  , START_TIME
  , END_TIME
FROM
    PRESENTATION
INNER JOIN
    COMPANY
ON
    PRESENTATION.BOOKED_COMPANY_ID = COMPANY.COMPANY_ID
INNER JOIN
    ROOM
ON
    PRESENTATION.BOOKED_ROOM_ID = ROOM.ROOM_ID;


SELECT
    *
FROM
    PRESENTATION_VIEW;